---
- name: Variables
  hosts: localhost
  vars: 
    fav_color: blue
    author: 'Sanjaay'
    ports: [21,22,23,45]
  tasks:
    - name: Print msg
      debug:
         msg: "My name is {{ author }} and color is {{ fav_color }}"
      loop: "{{ ports }}"
