---
- name: Jinja2 test
  hosts: localhost
  vars:
    webserver_message: "Im running to the finish line."
  tasks:
    - name: install apache2
      package:
        name: apache2
        state: latest
    - name: httpd start
      service:
        name: apache2
        state: started
    - name: create index file
      template:
        src: index.j2
        dest: /var/www/html/index.html
